/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as GuiasRouteImport } from './routes/guias'
import { Route as LegalidadRouteImport } from './routes/legalidad'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as VerificacionRouteImport } from './routes/verificacion'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as EjemplarIdRouteImport } from './routes/ejemplar.$id'
import { Route as EstatusIdRouteImport } from './routes/estatus.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiasRoute = GuiasRouteImport.update({
  id: '/guias',
  path: '/guias',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalidadRoute = LegalidadRouteImport.update({
  id: '/legalidad',
  path: '/legalidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificacionRoute = VerificacionRouteImport.update({
  id: '/verificacion',
  path: '/verificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EjemplarIdRoute = EjemplarIdRouteImport.update({
  id: '/ejemplar/$id',
  path: '/ejemplar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstatusIdRoute = EstatusIdRouteImport.update({
  id: '/estatus/$id',
  path: '/estatus/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/guias': typeof GuiasRoute
  '/legalidad': typeof LegalidadRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/verificacion': typeof VerificacionRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/ejemplar/$id': typeof EjemplarIdRoute
  '/estatus/$id': typeof EstatusIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/guias': typeof GuiasRoute
  '/legalidad': typeof LegalidadRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/verificacion': typeof VerificacionRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/ejemplar/$id': typeof EjemplarIdRoute
  '/estatus/$id': typeof EstatusIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/guias': typeof GuiasRoute
  '/legalidad': typeof LegalidadRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/verificacion': typeof VerificacionRoute
  '/api/chat': typeof ApiChatRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/ejemplar/$id': typeof EjemplarIdRoute
  '/estatus/$id': typeof EstatusIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explorar'
    | '/guias'
    | '/legalidad'
    | '/perfil'
    | '/publicar'
    | '/verificacion'
    | '/api/chat'
    | '/checkout/$id'
    | '/ejemplar/$id'
    | '/estatus/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explorar'
    | '/guias'
    | '/legalidad'
    | '/perfil'
    | '/publicar'
    | '/verificacion'
    | '/api/chat'
    | '/checkout/$id'
    | '/ejemplar/$id'
    | '/estatus/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explorar'
    | '/guias'
    | '/legalidad'
    | '/perfil'
    | '/publicar'
    | '/verificacion'
    | '/api/chat'
    | '/checkout/$id'
    | '/ejemplar/$id'
    | '/estatus/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExplorarRoute: typeof ExplorarRoute
  GuiasRoute: typeof GuiasRoute
  LegalidadRoute: typeof LegalidadRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  VerificacionRoute: typeof VerificacionRoute
  ApiChatRoute: typeof ApiChatRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  EjemplarIdRoute: typeof EjemplarIdRoute
  EstatusIdRoute: typeof EstatusIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guias': {
      id: '/guias'
      path: '/guias'
      fullPath: '/guias'
      preLoaderRoute: typeof GuiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legalidad': {
      id: '/legalidad'
      path: '/legalidad'
      fullPath: '/legalidad'
      preLoaderRoute: typeof LegalidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verificacion': {
      id: '/verificacion'
      path: '/verificacion'
      fullPath: '/verificacion'
      preLoaderRoute: typeof VerificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ejemplar/$id': {
      id: '/ejemplar/$id'
      path: '/ejemplar/$id'
      fullPath: '/ejemplar/$id'
      preLoaderRoute: typeof EjemplarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estatus/$id': {
      id: '/estatus/$id'
      path: '/estatus/$id'
      fullPath: '/estatus/$id'
      preLoaderRoute: typeof EstatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExplorarRoute: ExplorarRoute,
  GuiasRoute: GuiasRoute,
  LegalidadRoute: LegalidadRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  VerificacionRoute: VerificacionRoute,
  ApiChatRoute: ApiChatRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  EjemplarIdRoute: EjemplarIdRoute,
  EstatusIdRoute: EstatusIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
